config/routes.rb
Rails.application.routes.draw do
	root to: redirect('/requisitions')

  resources :orders
  resources :requisitions do
  	collection do
  		get 'tasks'
  	end
  	member do
  		get 'approve'
  		get 'received'
  	end	
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :requisition
end

app/models/requisition.rb
class Requisition < ApplicationRecord
    #enum loc: [:holsworthy, :victoria, :hampstead, :angelsea]
  after_update :create_attached_order, on: :update
  has_one :order

  def to_s 
  	"Requisition \##{id}"
  end

  def create_attached_order
  	if status == 'Approved' 
  		self.create_order({
  			:status => 'Pending'
  		})
  	end
  end	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  layout 'orders'
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.where status: 'Pending'
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        @order.requisition.update(status: 'Shipped')
        RestClient::Resource.new(APP_CONFIG[:insight_url], :verify_ssl => false, :user => APP_CONFIG[:insight_username], :password => APP_CONFIG[:insight_password]).post({
            "modelId" => "Resupply_Ky06ggwO",
            "correlationValue" => @order.requisition.id,
            "eventTime" => Time.now.strftime('%Y-%m-%dT%H:%M:%S'),
            "milestoneId" => "SuppliesSent"
          }.to_json, :content_type => 'application/json')
        format.html { redirect_to orders_url, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:sent, :comments, :status, :requisition_id)
    end
end

app/controllers/requisitions_controller.rb
class RequisitionsController < ApplicationController
  before_action :set_requisition, only: [:show, :edit, :update, :destroy, :approve, :received]

  # GET /requisitions
  # GET /requisitions.json
  def index
    @requisitions = Requisition.all.order(id: :desc)
  end

  def tasks
    @requisitions = Requisition.where status: ['Pending', 'Shipped']
  end

  def approve
    respond_to do |format|
      if @requisition.update(status: 'Approved')
        RestClient::Resource.new(APP_CONFIG[:insight_url], :verify_ssl => false, :user => APP_CONFIG[:insight_username], :password => APP_CONFIG[:insight_password]).post({
            "modelId" => "Resupply_Ky06ggwO",
            "correlationValue" => @requisition.id,
            "eventTime" => Time.now.strftime('%Y-%m-%dT%H:%M:%S'),
            "milestoneId" => "Approved"
          }.to_json, :content_type => 'application/json')
        format.html { redirect_to tasks_requisitions_url, notice: 'Requisition was successfully approved.' }
      else
        format.html { redirect_to tasks_requisitions_url, notice: 'Error when attempting to approve' }
      end
    end
  end

  def received
    respond_to do |format|
      if @requisition.update(status: 'Received')
        RestClient::Resource.new(APP_CONFIG[:insight_url], :verify_ssl => false, :user => APP_CONFIG[:insight_username], :password => APP_CONFIG[:insight_password]).post({
            "modelId" => "Resupply_Ky06ggwO",
            "correlationValue" => @requisition.id,
            "eventTime" => Time.now.strftime('%Y-%m-%dT%H:%M:%S'),
            "milestoneId" => "Received"
          }.to_json, :content_type => 'application/json')
        format.html { redirect_to tasks_requisitions_url, notice: 'Requisition was successfully marked as received.' }
      else
        format.html { redirect_to tasks_requisitions_url, notice: 'Error when attempting to receive' }
      end
    end
  end 

  # GET /requisitions/1
  # GET /requisitions/1.json
  def show
  end

  # GET /requisitions/new
  def new
    @requisition = Requisition.new
  end

  # GET /requisitions/1/edit
  def edit
  end

  # POST /requisitions
  # POST /requisitions.json
  def create
    @requisition = Requisition.new(requisition_params)
    respond_to do |format|
      if @requisition.save
        # Send to the Business Insight Model
        RestClient::Resource.new(APP_CONFIG[:insight_url], :verify_ssl => false, :user => APP_CONFIG[:insight_username], :password => APP_CONFIG[:insight_password]).post({
            "modelId" => "Resupply_Ky06ggwO",
            "measures" => [{
              "name" => "TotalCost",
              "value" => @requisition.amount
            }],
            "identifierValue" => @requisition.id,
            "correlationValue" => @requisition.id,
            "eventTime" => Time.now.strftime('%Y-%m-%dT%H:%M:%S'),
            "milestoneId" => "RequsitionRaised",
            "dimensions" => [ {
              "name" => "Location",
              "value" => @requisition.loc
            } ]
          }.to_json, :content_type=>'application/json')
        format.html { redirect_to requisitions_url, notice: 'Requisition was successfully created.' }
        format.json { render :show, status: :created, loc: @requisition }
      else
        format.html { render :new }
        format.json { render json: @requisition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requisitions/1
  # PATCH/PUT /requisitions/1.json
  def update
    respond_to do |format|
      if @requisition.update(requisition_params)
        format.html { redirect_to @requisition, notice: 'Requisition was successfully updated.' }
        format.json { render :show, status: :ok, loc: @requisition }
      else
        format.html { render :edit }
        format.json { render json: @requisition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requisitions/1
  # DELETE /requisitions/1.json
  def destroy
    @requisition.destroy
    respond_to do |format|
      format.html { redirect_to requisitions_url, notice: 'Requisition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_requisition
      @requisition = Requisition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def requisition_params
      params.require(:requisition).permit(:id, :title, :description, :amount, :status, :loc)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/requisitions_helper.rb
module RequisitionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Requisitions</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="reqs">
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Requisitions", "#", class: "navbar-brand" %>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/requisitions">Requisitions</a></li>
            <li><a href="/requisitions/tasks">Tasks</a></li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <%= msg %>
        <% end %>
      <% end %>

      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/layouts/orders.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Requisitions</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Orders System", "#", class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="/orders">Orders</a></li>        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/orders/_form.html.erb
<%= simple_form_for(@order, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @order.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h4>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :sent %>
  <%= f.input :comments %>
  <%= f.input :status, as: :hidden, input_html: {value: "Complete"} %>
  <%= f.button :submit, class: "btn-primary" %>

<% end %>

app/views/orders/edit.html.erb
<div class="page-header">
  <%= link_to orders_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @order, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing order</h1>
</div>

<%= render 'form' %>

app/views/orders/index.html.erb
<div class="page-header">
  <h1>Pending Orders</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Requisition</th>
            <th>Status</th>
            <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @orders) do |order| %>
            <td><%= order.requisition %></td>
            <td><%= order.status %></td>
            <td>
              <div class="btn-group">
                <%= link_to 'Edit', edit_order_path(order), class: 'btn btn-primary' %>
                <%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
              </div>
            </td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/orders/new.html.erb
<div class="page-header">
  <%= link_to orders_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New order</h1>
</div>

<%= render 'form' %>

app/views/orders/show.html.erb
<div class="page-header">
  <%= link_to orders_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_order_path(@order), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show order</h1>
</div>

<dl class="dl-horizontal">
  <dt>Sent:</dt>
  <dd><%= @order.sent %></dd>

  <dt>Comments:</dt>
  <dd><%= @order.comments %></dd>

  <dt>Status:</dt>
  <dd><%= @order.status %></dd>

  <dt>Requisition:</dt>
  <dd><%= @order.requisition %></dd>

</dl>

app/views/requisitions/_form.html.erb
<%= simple_form_for(@requisition, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @requisition.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@requisition.errors.count, "error") %> prohibited this requisition from being saved:</h4>

      <ul>
      <% @requisition.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :amount %>
  <%= f.input :status, as: :hidden, input_html: {value: "Pending"} %>
  <%= f.input :loc, collection: ['Holsworthy', 'Victoria Barracks', 'Angelsea', 'Hampstead'] %>
  <%= f.button :submit, class: "btn-primary" %>
<% end %>

app/views/requisitions/edit.html.erb
<div class="page-header">
  <%= link_to requisitions_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @requisition, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing requisition</h1>
</div>

<%= render 'form' %>

app/views/requisitions/index.html.erb
<div class="page-header">
  <%= link_to new_requisition_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Requisition
  <% end %>
  <h1>All Requisitions</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Id</th>
            <th>Title</th>
            <th>Amount</th>
            <th>Status</th>
            <th>Location</th>
            <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @requisitions) do |requisition| %>
            <td><%= link_to requisition.id, requisition %></td>
            <td><%= requisition.title %></td>
            <td><%= number_to_currency(requisition.amount) %></td>
            <td><%= requisition.status %></td>
            <td><%= requisition.loc %></td>
            <td>
              <div class="btn-group">
                <%= link_to 'Edit', edit_requisition_path(requisition), class: 'btn btn-primary' %>
                <%= link_to 'Destroy', requisition, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
              </div>
            </td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/requisitions/new.html.erb
<div class="page-header">
  <%= link_to requisitions_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New requisition</h1>
</div>

<%= render 'form' %>

app/views/requisitions/show.html.erb
<div class="page-header">
  <%= link_to requisitions_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_requisition_path(@requisition), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show requisition</h1>
</div>

<dl class="dl-horizontal">
  <dt>Id:</dt>
  <dd><%= @requisition.id %></dd>

  <dt>Title:</dt>
  <dd><%= @requisition.title %></dd>

  <dt>Description:</dt>
  <dd><%= @requisition.description %></dd>

  <dt>Amount:</dt>
  <dd><%= @requisition.amount %></dd>

  <dt>Status:</dt>
  <dd><%= @requisition.status %></dd>

  <dt>Location:</dt>
  <dd><%= @requisition.loc %></dd>

</dl>

app/views/requisitions/tasks.html.erb
<div class="page-header">
  <h1>Tasks</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Title</th>
        <th>Amount</th>
        <th>Status</th>
        <th>Actions</th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @requisitions) do |req| %>
        <td><%= req.title %></td>
        <td><%= number_to_currency(req.amount) %></td>
        <td><%= req.status %></td>
        <td>
          <% if req.status == 'Shipped' %>
            <%= link_to 'Received', received_requisition_path(req), class: 'btn btn-primary'  %>
          <% else %>
            <%= link_to 'Approve', approve_requisition_path(req), class: 'btn btn-primary' %>
          <% end %>    
        </td>
      <% end %>
    </tbody>
  </table>
</div>